// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: channels.sql

package database

import (
	"context"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name) VALUES (?) RETURNING id, name, created_at
`

func (q *Queries) CreateChannel(ctx context.Context, name string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel, name)
	var i Channel
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
