// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: messages.sql

package database

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (user_id, channel_id, message) VALUES (?, ?, ?) RETURNING id, user_id, channel_id, message, created_at, updated_at
`

type CreateMessageParams struct {
	UserID    int64  `json:"user_id"`
	ChannelID int64  `json:"channel_id"`
	Message   string `json:"message"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.UserID, arg.ChannelID, arg.Message)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
